// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
///import 'firebase_options.dart';
/// // ...
///await Firebase.initializeApp(
///  options = DefaultFirebaseOptions.currentPlatform,
///);
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRI8HIuMI1GqqeAkwMUFpsnxpG9u2r4EA',
    appId: '1:510434870925:web:9af529fa45c2015c6404c4',
    messagingSenderId: '510434870925',
    projectId: 'first-notes-app-34e3f',
    authDomain: 'first-notes-app-34e3f.firebaseapp.com',
    storageBucket: 'first-notes-app-34e3f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIJEV-tiKXhO0idU8tU8CQiA5E10Guh10',
    appId: '1:510434870925:android:73410ff1d76bb6566404c4',
    messagingSenderId: '510434870925',
    projectId: 'first-notes-app-34e3f',
    storageBucket: 'first-notes-app-34e3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVCr17mQ_zfAoyL9dg8bKuWlWm5_0D14w',
    appId: '1:510434870925:ios:e3cf388be54826b06404c4',
    messagingSenderId: '510434870925',
    projectId: 'first-notes-app-34e3f',
    storageBucket: 'first-notes-app-34e3f.firebasestorage.app',
    iosBundleId: 'com.example.loginAuth',
  );
}
